updated myproxy certs from xsede ca pack, added logging for trust store locations at debug level, seemingly working rpm builder scripts, re-enabled credential checking in serverwsdoallrec to see if tls cert is associated with all certs (currently warns but does not axe them to ensure we're not hosing our replication code), vana's changes for fixing genesis BES handling of MPI properties in jsdl, modified all template scripts to use install4j tag for install dir.

diff --git a/scripts/cert-tool b/scripts/cert-tool
--- a/scripts/cert-tool
+++ b/scripts/cert-tool
@@ -1,3 +1,16 @@
 #!/bin/sh
 
-"$JAVA_HOME/bin/java" -classpath "%{INSTALL_PATH}/bundles/org.apache.commons.logging_1.1.1.v201101211721.jar:%{INSTALL_PATH}/ext/log4j-1.2.17.jar:%{INSTALL_PATH}/lib:%{INSTALL_PATH}/ext/gffs-basics.jar" "-Dlog4j.configuration=%{CLIENT_LOG4JCONFIG}" "-Djava.library.path=%{INSTALL_PATH}/%{GENII_JNI_PATH}" edu.virginia.vcgr.appmgr.launcher.ApplicationLauncher "%{INSTALL_PATH}/ext/genii-certtool-application.properties" "$@"
+java_app="${installer:sys.installationDir}/jre/bin/java"
+if [ ! -f "$java_app" ]; then
+  java_app="$JAVA_HOME/bin/java"
+  if [ ! -f "$java_app" ]; then
+    java_app="$(which java)"
+    if [ ! -f "$java_app" ]; then
+      echo "ERROR: could not deduce location of java from search path, JAVA_HOME or"
+      echo "the Genesis II GFFS installation directory."
+      exit 1
+    fi
+  fi
+fi
+
+"$java_app" -classpath "${installer:sys.installationDir}/bundles/org.apache.commons.logging_1.1.1.v201101211721.jar:${installer:sys.installationDir}/ext/log4j-1.2.17.jar:${installer:sys.installationDir}/lib:${installer:sys.installationDir}/ext/gffs-basics.jar" "-Dlog4j.configuration=%{CLIENT_LOG4JCONFIG}" "-Djava.library.path=${installer:sys.installationDir}/%{GENII_JNI_PATH}" edu.virginia.vcgr.appmgr.launcher.ApplicationLauncher "${installer:sys.installationDir}/ext/genii-certtool-application.properties" "$@"
diff --git a/scripts/grid b/scripts/grid
--- a/scripts/grid
+++ b/scripts/grid
@@ -1,5 +1,18 @@
 #!/bin/sh
 
-export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:%{INSTALL_PATH}/%{GENII_JNI_PATH}"
+export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:${installer:sys.installationDir}/%{GENII_JNI_PATH}"
 
-"$JAVA_HOME/bin/java" -Xms128M -Xmx768M -classpath "%{INSTALL_PATH}/bundles/org.apache.commons.logging_1.1.1.v201101211721.jar:%{INSTALL_PATH}/ext/log4j-1.2.17.jar:%{INSTALL_PATH}/lib:%{INSTALL_PATH}/ext/gffs-basics.jar:%{INSTALL_PATH}/ext/gffs-structure.jar:%{INSTALL_PATH}/ext/gffs-webservices.jar:%{INSTALL_PATH}/ext/axis/axis.jar:%{INSTALL_PATH}/ext/derby.jar" "-Dlog4j.configuration=%{CLIENT_LOG4JCONFIG}" "-Djava.library.path=%{INSTALL_PATH}/%{GENII_JNI_PATH}" "-Dedu.virginia.vcgr.genii.install-base-dir=%{INSTALL_PATH}" edu.virginia.vcgr.appmgr.launcher.ApplicationLauncher "%{INSTALL_PATH}/ext/genii-client-application.properties" "$@"
+java_app="${installer:sys.installationDir}/jre/bin/java"
+if [ ! -f "$java_app" ]; then
+  java_app="$JAVA_HOME/bin/java"
+  if [ ! -f "$java_app" ]; then
+    java_app="$(which java)"
+    if [ ! -f "$java_app" ]; then
+      echo "ERROR: could not deduce location of java from search path, JAVA_HOME or"
+      echo "the Genesis II GFFS installation directory."
+      exit 1
+    fi
+  fi
+fi
+
+"$java_app" -Xms128M -Xmx768M -classpath "${installer:sys.installationDir}/bundles/org.apache.commons.logging_1.1.1.v201101211721.jar:${installer:sys.installationDir}/ext/log4j-1.2.17.jar:${installer:sys.installationDir}/lib:${installer:sys.installationDir}/ext/gffs-basics.jar:${installer:sys.installationDir}/ext/gffs-structure.jar:${installer:sys.installationDir}/ext/gffs-webservices.jar:${installer:sys.installationDir}/ext/axis/axis.jar:${installer:sys.installationDir}/ext/derby.jar" "-Dlog4j.configuration=%{CLIENT_LOG4JCONFIG}" "-Djava.library.path=${installer:sys.installationDir}/%{GENII_JNI_PATH}" "-Dedu.virginia.vcgr.genii.install-base-dir=${installer:sys.installationDir}" edu.virginia.vcgr.appmgr.launcher.ApplicationLauncher "${installer:sys.installationDir}/ext/genii-client-application.properties" "$@"
